--- #YAML:1.0
name:               Speech-Swift-Simple
version:            1.1
abstract:           Simplified extension for Speech::Swift, a 
author:
    - Mike Pultz <mike@mikepultz.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Speech::Swift:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
